#Alg Configs:

Signal_configs:
  #选择实时峰谷图成像方法，0表示使用截取成像，1表示使用插值成像,默认值使用插值成像
  pp_method : 1

  #选择实时峰谷图成像方法是否使用一点多次扫描取平均，0表示不使用，1表示使用多次平均,默认值不使用
  open_mean : 1

  #当实时峰谷图成像方法选择1时生效，使用何种差值方式成像，只有三种方式可选，['nearest','linear','cubic']，默认选择nearest
  griddata_method : nearest

  #对解包算法增加主峰对齐，0表示关闭，1表示开启,默认关闭
  align : 1

  #上位机软件数据分析展示到最大太赫兹数，默认3
  thz_max : 6

  #是否对信号进行Savitzky-Golay滤波处理，默认值为0不进行滤波，1为进行浅度去毛刺，2为进行深度去毛刺
  SG : 0

  #是否对信号进行中值滤波处理，默认值为0不进行滤波，其他值必须设置为奇数才进行中值滤波
  medianf : 0

  #是否对信号进行带通滤波处理，选择类型bandpass，lowpass，highpass，不开启填写none
  filter_name : none

  #是否对信号进行低通滤波处理进行阈值选择
  lowpass_value : 0.8

  #是否对信号进行高通滤波处理进行阈值选择
  highpass_value : 0.006

  #是否对信号进行小波滤波处理，默认值为0不进行滤波，1进行小波变换
  dwt : 0

  #是否对信号进行小波滤波处理，在上述值为1下生效，小波变换例如：db13, db25, db31, sym11, sym13, coif17,  ......，选择其中之一。
  wave_name : db13

  #是否对信号进行主峰对齐，如果要对齐则修改下面参数为1，如果不对齐则默认参数为0.
  align_signal : 1

  #是否对信号做滑动移动平均，默认不做参数为1，若要使用生效需输入大于1的整数
  if_moveAverage : 1


Imaging_configs:
  #实时峰谷图变换
  #参数0显示的是不变换
  #参数1显示的是左右翻转
  #参数2显示的是上下翻转
  #参数3显示的是左右上下全翻转
  #参数4显示的是逆时针差90度
  #参数5显示的是逆时针差90度后左右翻转
  #参数6显示的是逆时针差90度后上下翻转
  #参数7显示的是顺时针差90度
  #参数8显示的是顺时针差90度后左右翻转
  #参数9显示的是顺时针差90度后上下翻转
  pp_image : 2

  #参数0显示的是xy截面、xz截面、yz截面都是正向
  #参数1显示的是xy截面、xz截面、yz截面都是左右反向
  #参数2显示的是xy截面、xz截面、yz截面都是上下反向
  #参数3显示的是xy截面、xz截面、yz截面左右上下全反向
  #参数4显示的是xy截面、xz截面、yz截面都是逆时针差90度
  #参数5显示的是xy截面、xz截面、yz截面逆时针差90度后左右反向
  #参数6显示的是xy截面、xz截面、yz截面逆时针差90度后上下反向
  #参数7显示的是xy截面、xz截面、yz截面都是顺时针差90度
  #参数8显示的是xy截面、xz截面、yz截面顺时针差90度后左右反向
  #参数9显示的是xy截面、xz截面、yz截面顺时针差90度后上下反向
  xy : 1
  xz : 2
  yz : 2

  #三维层析成像信号进行删除小于步进的点，取值范围为0.1-0.5，默认值为0.5，在采集点数少的情况下请改为0.1。
  delete_d : 0.1

  #三维层析成像对信号阈值高低截断处理，默认值为0，当值为1时下面两个高低截断功能才生效。
  use_threshold : 0

  #三维层析成像显示进行信号阈值截断，阈值默认大小为-10000，即所有三维信号大于-10000的保留，小于-10000的删除。
  min_threshold : -10000

  #三维层析成像对信号高于某阈值的信号进行置零，默认值为10000，即高于10000的信号置零，低于10000的信号保留
  max_threshold : 10000

  #机械臂成像的坐标文件路径
  robot_xyz : E:\data\IC_1mm.csv

  #机械臂成像是否删除0,0表示不删除，1表示删除1个点
  robot_delete: 1


System_configs:
  #目前二维扫描平台有两种，一种是自研二维平台，二是卓列汉光平台，不同平台成像会出现反向问题。
  #在此加入配置文件进行选择调用。1代表自研二维平台，2代表卓列汉光。修改参数进行配置。
  platform : 1

  #新移动平台精度是旧平台的两倍,旧平台精度设置为1，新平台精度设置为2
  precision : 2

  #只取延迟线正向采集数据标记为0，只取延迟线反向采集数据标记为1，延迟线正向反向采集数据都要标记为2
  delay_line : 2

  #延迟线长度参数配置
  delay_length : 0.5

  #旋转延迟线几倍光程参数配置
  shine_length : 6


