# 左侧
from PyQt5.Qt import *
from PyQt5.QtWidgets import QLabel, QWidget, QHBoxLayout, QCheckBox, QGroupBox
from PyQt5 import QtCore, QtWidgets

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDropListItem.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class SettingDropListItem(QWidget):
    def __init__(self):
        super(SettingDropListItem, self).__init__(None)
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(20, 10, 0, 10)
        self.gridLayout.setHorizontalSpacing(15)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblIcon = QtWidgets.QLabel(self.widget)
        self.lblIcon.setMinimumSize(QtCore.QSize(25, 25))
        self.lblIcon.setMaximumSize(QtCore.QSize(25, 25))
        self.lblIcon.setText("")
        self.lblIcon.setObjectName("lblIcon")
        self.gridLayout.addWidget(self.lblIcon, 0, 0, 1, 1)
        self.lblName = QtWidgets.QLabel(self.widget)
        self.lblName.setText("")
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 1, 1, 1)
        self.setLayout(self.gridLayout)
