# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiCxGpDataMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1267, 721)
        Form.setStyleSheet("QGroupBox{border:none;background-color:#FFFFFF;}\n"
"QPushButton{font-family:\"宋体\";font-size:11pt;color:white;background:transparent;}\n"
"QCheckBox{background:transparent;margin-left:5px;}\n"
"QScrollArea{background:transparent;border:none;}\n"
"#scrollAreaWidgetContents{background-color:#FFFFFF;}\n"
"QComboBox{color:#FF4D4D4D;}\n"
"QComboBox QAbstractItemView::item { height: 25px; color:#FF4D4D4D; }\n"
"#lineSearch{background-color:#FFEBEBEB;color:#FF4D4D4D;border-radius: 15px; border: 2px; padding:0 0 0 10;}\n"
"#btnCxGpDataDel{background-color: rgb(255,62,62);}\n"
"#gbxCxGpDataTableHeader{background-color: #FF00A3DA;}\n"
"#gbxCxGpDataTableHeader QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left}\n"
"\n"
"#btnCxGpDataDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#btnCxGpDataDel:hover{background-color:rgb(255, 111, 92);}\n"
"#btnPrev{background-color:#FF00A3DA;border:none;}\n"
"#btnPrev:hover{background-color:#8F00A3DA;}\n"
"#btnNext{background-color:#FF00A3DA;border:none;}\n"
"#btnNext:hover{background-color:#8F00A3DA;}\n"
"QListWidget{border:none;background:transparent;}\n"
"QListWidget::item{border-bottom:1px solid black;}\n"
"QListWidget::item .QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left;}\n"
"QListWidget::item .QPushButton{font-size:9pt;}\n"
"QListWidget::item:hover{background-color:#e5f3ff;}\n"
"QListWidget::item:pressed{background-color:#cde8ff;color:#FF4D4D4D}\n"
"\n"
"\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical {width: 5px;}\n"
"QScrollBar:vertical{width:5px;background:#FFFFFF; margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:5px;background:transparent;border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:5px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"QCheckBox{background:transparent;}\n"
"QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } \n"
"QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}\n"
"#optView{color:#4454a6;}\n"
"#optExport{color:#0ab363;}\n"
"#optDel{color:#e54356;}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_12 = QtWidgets.QGroupBox(Form)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(9, -1, 30, 10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.btnCxGpDataDel = QtWidgets.QPushButton(self.groupBox_12)
        self.btnCxGpDataDel.setMinimumSize(QtCore.QSize(80, 30))
        self.btnCxGpDataDel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnCxGpDataDel.setFont(font)
        self.btnCxGpDataDel.setStyleSheet("")
        self.btnCxGpDataDel.setObjectName("btnCxGpDataDel")
        self.gridLayout_4.addWidget(self.btnCxGpDataDel, 1, 3, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineSearch.setMinimumSize(QtCore.QSize(280, 30))
        self.lineSearch.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineSearch.setFont(font)
        self.lineSearch.setTabletTracking(False)
        self.lineSearch.setStyleSheet("")
        self.lineSearch.setInputMask("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineSearch.setCursorPosition(0)
        self.lineSearch.setClearButtonEnabled(False)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout_4.addWidget(self.lineSearch, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 2, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(Form)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gbxContent = QtWidgets.QGroupBox(self.groupBox_11)
        self.gbxContent.setStyleSheet("")
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbxContent)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.gbxContent)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1267, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxCxGpDataTableHeader = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gbxCxGpDataTableHeader.setMinimumSize(QtCore.QSize(0, 30))
        self.gbxCxGpDataTableHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gbxCxGpDataTableHeader.setStyleSheet("")
        self.gbxCxGpDataTableHeader.setTitle("")
        self.gbxCxGpDataTableHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.gbxCxGpDataTableHeader.setObjectName("gbxCxGpDataTableHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxCxGpDataTableHeader)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_10 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_10.setMinimumSize(QtCore.QSize(30, 0))
        self.label_10.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.label_5 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_7 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_7.setMinimumSize(QtCore.QSize(80, 0))
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_2 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_3.setMinimumSize(QtCore.QSize(220, 0))
        self.label_3.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_8 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_8.setMinimumSize(QtCore.QSize(100, 0))
        self.label_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_13 = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.label_13.setMinimumSize(QtCore.QSize(158, 0))
        self.label_13.setMaximumSize(QtCore.QSize(158, 16777215))
        self.label_13.setSizeIncrement(QtCore.QSize(0, 0))
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lblOpt = QtWidgets.QLabel(self.gbxCxGpDataTableHeader)
        self.lblOpt.setMinimumSize(QtCore.QSize(90, 0))
        self.lblOpt.setMaximumSize(QtCore.QSize(90, 16777215))
        self.lblOpt.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblOpt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOpt.setObjectName("lblOpt")
        self.horizontalLayout.addWidget(self.lblOpt)
        self.verticalLayout_2.addWidget(self.gbxCxGpDataTableHeader)
        self.listWidgetCxGpData = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidgetCxGpData.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.listWidgetCxGpData.setStyleSheet("")
        self.listWidgetCxGpData.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetCxGpData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetCxGpData.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetCxGpData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetCxGpData.setObjectName("listWidgetCxGpData")
        self.verticalLayout_2.addWidget(self.listWidgetCxGpData)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.gbxContent)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnPrev = QtWidgets.QPushButton(self.groupBox)
        self.btnPrev.setMinimumSize(QtCore.QSize(80, 30))
        self.btnPrev.setMaximumSize(QtCore.QSize(80, 30))
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout_2.addWidget(self.btnPrev)
        self.cbxPages = QtWidgets.QComboBox(self.groupBox)
        self.cbxPages.setMinimumSize(QtCore.QSize(80, 32))
        self.cbxPages.setMaximumSize(QtCore.QSize(80, 32))
        self.cbxPages.setSizeIncrement(QtCore.QSize(0, 0))
        self.cbxPages.setStyleSheet("background-color: #FFEBEBEB; border:none;")
        self.cbxPages.setEditable(False)
        self.cbxPages.setCurrentText("")
        self.cbxPages.setPlaceholderText("")
        self.cbxPages.setObjectName("cbxPages")
        self.horizontalLayout_2.addWidget(self.cbxPages)
        self.btnNext = QtWidgets.QPushButton(self.groupBox)
        self.btnNext.setMinimumSize(QtCore.QSize(80, 30))
        self.btnNext.setMaximumSize(QtCore.QSize(80, 30))
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_9.addWidget(self.gbxContent)
        self.verticalLayout.addWidget(self.groupBox_11)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_4.setText(_translate("Form", "成像光谱数据管理"))
        self.btnCxGpDataDel.setText(_translate("Form", "删除"))
        self.lineSearch.setPlaceholderText(_translate("Form", "请以操作员或日期为条件查询"))
        self.label_10.setText(_translate("Form", "选择"))
        self.label_5.setText(_translate("Form", "名称"))
        self.label_9.setText(_translate("Form", "类型"))
        self.label.setText(_translate("Form", "扫描时间"))
        self.label_7.setText(_translate("Form", "厚度"))
        self.label_2.setText(_translate("Form", "分频系数"))
        self.label_3.setText(_translate("Form", "扫描范围"))
        self.label_8.setText(_translate("Form", "操作员"))
        self.label_13.setText(_translate("Form", "日期"))
        self.lblOpt.setText(_translate("Form", "操作"))
        self.btnPrev.setText(_translate("Form", "上一页"))
        self.btnNext.setText(_translate("Form", "下一页"))
