# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDemoCategory.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 454)
        Form.setStyleSheet("QGroupBox{border:none}\n"
"QLabel{background-color:transparent;color:#FF4D4D4D;}\n"
"QPushButton{font-size:10pt;}\n"
"QTreeWidget{background-color:transparent;border:none;color:white;}\n"
"#lblFormName{font-size:14pt;}\n"
"#lblTitle{font-size:10pt;}\n"
"#gbxTop{background-color:#FF00A3DA}\n"
"#gbxContent{background-color:#FFFFFF}\n"
"#gbxClose{background-color:transparent;}\n"
"#gbxContent{border:1px solid gray;}\n"
"#btnClose{border-image: url(./Res/叉.png)}\n"
"#btnCancel,#btnDel{color: rgb(255, 61, 55);}\n"
"#txtName{color:#FF4D4D4D;background-color:transparent;}\n"
"\n"
"#btnTopItemAdd{background-color:#FF00A3DA;border:none;}\n"
"#btnTopItemAdd:hover{background-color:#8F00A3DA;}\n"
"#btnOk{background-color:#FF00A3DA;border:none;}\n"
"#btnOk:hover{background-color:#8F00A3DA;}\n"
"\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical{width:5px;background:transparent;margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:5px;background:rgba(0,0,0,10%);border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:5px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gbxContent = QtWidgets.QGroupBox(Form)
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxContent)
        self.verticalLayout.setContentsMargins(2, 2, 2, 6)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxTop = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxTop.setMinimumSize(QtCore.QSize(0, 50))
        self.gbxTop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gbxTop.setTitle("")
        self.gbxTop.setObjectName("gbxTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxTop)
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFormName = QtWidgets.QLabel(self.gbxTop)
        self.lblFormName.setObjectName("lblFormName")
        self.horizontalLayout.addWidget(self.lblFormName)
        self.btnClose = QtWidgets.QPushButton(self.gbxTop)
        self.btnClose.setMinimumSize(QtCore.QSize(20, 20))
        self.btnClose.setMaximumSize(QtCore.QSize(20, 20))
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.gbxTop)
        self.gbxBottom = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxBottom.setTitle("")
        self.gbxBottom.setObjectName("gbxBottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxBottom)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.gbxBottom)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setContentsMargins(0, 0, 9, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(20, 6, 6, 6)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblTitle = QtWidgets.QLabel(self.groupBox)
        self.lblTitle.setMinimumSize(QtCore.QSize(90, 0))
        self.lblTitle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblTitle.setObjectName("lblTitle")
        self.horizontalLayout_3.addWidget(self.lblTitle)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btnTopItemAdd = QtWidgets.QPushButton(self.groupBox)
        self.btnTopItemAdd.setMinimumSize(QtCore.QSize(80, 30))
        self.btnTopItemAdd.setMaximumSize(QtCore.QSize(80, 30))
        self.btnTopItemAdd.setObjectName("btnTopItemAdd")
        self.horizontalLayout_3.addWidget(self.btnTopItemAdd)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(self.gbxBottom)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox_3)
        self.treeWidget.setHeaderHidden(True)
        self.treeWidget.setExpandsOnDoubleClick(False)
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")
        self.horizontalLayout_5.addWidget(self.treeWidget)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gbxBottom)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOk = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOk.setMinimumSize(QtCore.QSize(80, 30))
        self.btnOk.setMaximumSize(QtCore.QSize(80, 30))
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_2.addWidget(self.btnOk)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.gbxBottom)
        self.horizontalLayout_6.addWidget(self.gbxContent)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblFormName.setText(_translate("Form", "样品分类"))
        self.lblTitle.setText(_translate("Form", "样品分类列表"))
        self.btnTopItemAdd.setText(_translate("Form", "添加"))
        self.btnOk.setText(_translate("Form", "确 定"))
