# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiDropList.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DropBoxForm(object):
    def setupUi(self, DropBoxForm):
        DropBoxForm.setObjectName("DropBoxForm")
        DropBoxForm.resize(170, 185)
        DropBoxForm.setMinimumSize(QtCore.QSize(170, 0))
        DropBoxForm.setMaximumSize(QtCore.QSize(170, 16777215))
        DropBoxForm.setStyleSheet("QLabel,QPushButton{background:transparent;}\n"
"#gbxContent{border:none;}\n"
"#gbxTop{background-color:#FF00A3DA;border-bottom:1px solid gray;border-top:none;border-left:none;border-right:none;}\n"
"#gbxBottom{background-color:#FF00A3DA;border:none;}\n"
"QLabel{color:#FF4D4D4D;font-size:9pt;}\n"
"QListWidget{border:none;background:transparent;}\n"
"\n"
"\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(DropBoxForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxContent = QtWidgets.QGroupBox(DropBoxForm)
        self.gbxContent.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxContent)
        self.verticalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxTop = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxTop.setMinimumSize(QtCore.QSize(0, 45))
        self.gbxTop.setMaximumSize(QtCore.QSize(16777215, 45))
        self.gbxTop.setObjectName("gbxTop")
        self.gridLayout = QtWidgets.QGridLayout(self.gbxTop)
        self.gridLayout.setContentsMargins(5, 0, 3, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblName = QtWidgets.QLabel(self.gbxTop)
        self.lblName.setMinimumSize(QtCore.QSize(0, 0))
        self.lblName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblName.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblName.setAlignment(QtCore.Qt.AlignCenter)
        self.lblName.setObjectName("lblName")
        self.gridLayout.addWidget(self.lblName, 0, 1, 1, 1)
        self.lblPhone = QtWidgets.QLabel(self.gbxTop)
        self.lblPhone.setMinimumSize(QtCore.QSize(0, 25))
        self.lblPhone.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lblPhone.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblPhone.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPhone.setObjectName("lblPhone")
        self.gridLayout.addWidget(self.lblPhone, 1, 1, 1, 1)
        self.lblIcon = QtWidgets.QLabel(self.gbxTop)
        self.lblIcon.setMinimumSize(QtCore.QSize(32, 32))
        self.lblIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.lblIcon.setText("")
        self.lblIcon.setScaledContents(True)
        self.lblIcon.setObjectName("lblIcon")
        self.gridLayout.addWidget(self.lblIcon, 0, 0, 2, 1)
        self.btnEdit = QtWidgets.QPushButton(self.gbxTop)
        self.btnEdit.setMinimumSize(QtCore.QSize(16, 16))
        self.btnEdit.setMaximumSize(QtCore.QSize(16, 16))
        self.btnEdit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Image/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEdit.setIcon(icon)
        self.btnEdit.setIconSize(QtCore.QSize(16, 16))
        self.btnEdit.setDefault(False)
        self.btnEdit.setFlat(False)
        self.btnEdit.setObjectName("btnEdit")
        self.gridLayout.addWidget(self.btnEdit, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.gbxTop)
        self.gbxBottom = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxBottom.setTitle("")
        self.gbxBottom.setObjectName("gbxBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxBottom)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.gbxBottom)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.listWidget)
        self.verticalLayout_2.addWidget(self.gbxBottom)
        self.verticalLayout.addWidget(self.gbxContent)

        self.retranslateUi(DropBoxForm)
        QtCore.QMetaObject.connectSlotsByName(DropBoxForm)

    def retranslateUi(self, DropBoxForm):
        _translate = QtCore.QCoreApplication.translate
        DropBoxForm.setWindowTitle(_translate("DropBoxForm", "Form"))
        self.lblName.setText(_translate("DropBoxForm", "admin"))
        self.lblPhone.setText(_translate("DropBoxForm", "19981278985"))
import thzres_rc
