# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiEditPwd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(402, 302)
        Dialog.setMinimumSize(QtCore.QSize(402, 302))
        Dialog.setMaximumSize(QtCore.QSize(402, 302))
        Dialog.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        Dialog.setStyleSheet("QGroupBox{border:none;}\n"
"QPushButton,QLabel,QLineEdit{background:transparent;color:white;border:none;}\n"
"QLineEdit{background-color:rgb(50,53,66);}\n"
"QPushButton{color:#FFFFFFFF;border:none;}\n"
"QPushButton:hover{background-color:#FFFF0000; color: #FFFFFFFF;}\n"
"#gbxTop{background-color: rgb(50,53,66);border-left:1px solid gray;border-top:1px solid gray;border-right:1px solid gray;}\n"
"#gbxBottom{background-color: rgb(68,71,86);border-left:1px solid gray;border-bottom:1px solid gray;border-right:1px solid gray;}\n"
"#lblIcon{border-radius:40px;background-color:gray;}\n"
"#btnOk{background-color:#FF4463BE;border:none;}\n"
"#btnOk:hover{background-color: rgb(68, 87, 145); color: #FFFFFFFF;}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxTop = QtWidgets.QGroupBox(Dialog)
        self.gbxTop.setMinimumSize(QtCore.QSize(0, 50))
        self.gbxTop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gbxTop.setTitle("")
        self.gbxTop.setObjectName("gbxTop")
        self.btnClose = QtWidgets.QPushButton(self.gbxTop)
        self.btnClose.setGeometry(QtCore.QRect(360, 10, 30, 30))
        self.btnClose.setMinimumSize(QtCore.QSize(30, 30))
        self.btnClose.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Webdings")
        self.btnClose.setFont(font)
        self.btnClose.setObjectName("btnClose")
        self.label_4 = QtWidgets.QLabel(self.gbxTop)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 100, 30))
        self.label_4.setMinimumSize(QtCore.QSize(100, 30))
        self.label_4.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.gbxTop)
        self.gbxBottom = QtWidgets.QGroupBox(Dialog)
        self.gbxBottom.setTitle("")
        self.gbxBottom.setAlignment(QtCore.Qt.AlignCenter)
        self.gbxBottom.setObjectName("gbxBottom")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxBottom)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gbxBottom)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.txtConfirmPwd = QtWidgets.QLineEdit(self.gbxBottom)
        self.txtConfirmPwd.setMinimumSize(QtCore.QSize(200, 30))
        self.txtConfirmPwd.setMaximumSize(QtCore.QSize(150, 30))
        self.txtConfirmPwd.setObjectName("txtConfirmPwd")
        self.gridLayout.addWidget(self.txtConfirmPwd, 2, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gbxBottom)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gbxBottom)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 1, 1, 1)
        self.txtOldPwd = QtWidgets.QLineEdit(self.gbxBottom)
        self.txtOldPwd.setMinimumSize(QtCore.QSize(200, 30))
        self.txtOldPwd.setMaximumSize(QtCore.QSize(200, 30))
        self.txtOldPwd.setObjectName("txtOldPwd")
        self.gridLayout.addWidget(self.txtOldPwd, 0, 3, 1, 1)
        self.txtNewPwd = QtWidgets.QLineEdit(self.gbxBottom)
        self.txtNewPwd.setMinimumSize(QtCore.QSize(200, 30))
        self.txtNewPwd.setMaximumSize(QtCore.QSize(150, 30))
        self.txtNewPwd.setObjectName("txtNewPwd")
        self.gridLayout.addWidget(self.txtNewPwd, 1, 3, 1, 1)
        self.btnOk = QtWidgets.QPushButton(self.gbxBottom)
        self.btnOk.setMinimumSize(QtCore.QSize(80, 40))
        self.btnOk.setMaximumSize(QtCore.QSize(80, 40))
        self.btnOk.setObjectName("btnOk")
        self.gridLayout.addWidget(self.btnOk, 3, 3, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.gridLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.gbxBottom)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnClose.setText(_translate("Dialog", "r"))
        self.label_4.setText(_translate("Dialog", "密码修改"))
        self.label.setText(_translate("Dialog", "旧密码:"))
        self.label_2.setText(_translate("Dialog", "新密码:"))
        self.label_3.setText(_translate("Dialog", "确认密码:"))
        self.btnOk.setText(_translate("Dialog", "确 定"))
