# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiRightEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RightEditForm(object):
    def setupUi(self, RightEditForm):
        RightEditForm.setObjectName("RightEditForm")
        RightEditForm.resize(625, 625)
        RightEditForm.setMinimumSize(QtCore.QSize(625, 625))
        RightEditForm.setMaximumSize(QtCore.QSize(625, 625))
        RightEditForm.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"color:white;\n"
"border:none;\n"
"QTreeWidget#treeRights::branch:has-children:!has-siblings:closed;\n"
"QTreeWidget#treeRights::branch:closed:has-children:has-siblings{border-image: none; image: url(:./Res/arrowDown.png);};\n"
"QTreeWidget#treeRights::branch:open:has-children:!has-siblings;\n"
"QTreeWidget#treeRights::branch:open:has-children:has-siblings{border-image: none; image: url(:./Res/arrowDown.png);};")
        self.horizontalLayout = QtWidgets.QHBoxLayout(RightEditForm)
        self.horizontalLayout.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(RightEditForm)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 76))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 76))
        self.groupBox.setStyleSheet("background-color: rgb(50, 53, 66);\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btnClose = QtWidgets.QPushButton(self.groupBox)
        self.btnClose.setGeometry(QtCore.QRect(560, 20, 25, 25))
        self.btnClose.setMinimumSize(QtCore.QSize(25, 25))
        self.btnClose.setMaximumSize(QtCore.QSize(25, 25))
        self.btnClose.setStyleSheet("QPushButton{border-image: url(./Res/叉.png)}")
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(RightEditForm)
        self.groupBox_2.setStyleSheet("background-color: rgb(68, 71, 86);")
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.treeRights = QtWidgets.QTreeWidget(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.treeRights.setFont(font)
        self.treeRights.setStyleSheet("")
        self.treeRights.setHeaderHidden(True)
        self.treeRights.setColumnCount(2)
        self.treeRights.setObjectName("treeRights")
        self.treeRights.headerItem().setText(0, "1")
        self.treeRights.headerItem().setText(1, "2")
        self.horizontalLayout_2.addWidget(self.treeRights)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(RightEditForm)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 76))
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 76))
        self.groupBox_3.setStyleSheet("background-color: rgb(68, 71, 86);")
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.btnOK = QtWidgets.QPushButton(self.groupBox_3)
        self.btnOK.setGeometry(QtCore.QRect(240, 10, 116, 44))
        self.btnOK.setMinimumSize(QtCore.QSize(116, 44))
        self.btnOK.setMaximumSize(QtCore.QSize(116, 44))
        self.btnOK.setAutoFillBackground(False)
        self.btnOK.setStyleSheet("background-color: rgb(68, 99, 190);")
        self.btnOK.setObjectName("btnOK")
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(RightEditForm)
        QtCore.QMetaObject.connectSlotsByName(RightEditForm)

    def retranslateUi(self, RightEditForm):
        _translate = QtCore.QCoreApplication.translate
        RightEditForm.setWindowTitle(_translate("RightEditForm", "Form"))
        self.label.setText(_translate("RightEditForm", "权限分配"))
        self.btnOK.setText(_translate("RightEditForm", "确定"))
