# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiRoleMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiRoleMgr(object):
    def setupUi(self, UiRoleMgr):
        UiRoleMgr.setObjectName("UiRoleMgr")
        UiRoleMgr.resize(997, 572)
        UiRoleMgr.setStyleSheet(".QGroupBox{border:none;background-color:#FFFFFF;}\n"
".QPushButton{font-family:\"宋体\";font-size:11pt;color:white;background:transparent;}\n"
".QCheckBox{background:transparent;margin-left:5px;}\n"
"#lineSearch{background-color:#FFEBEBEB;color:#FF4D4D4D;border-radius: 15px; border: 2px; padding:0 0 0 10;}\n"
"#btnRoleAdd{background-color: rgb(68,99,190);}\n"
"#btnRoleDel{background-color: rgb(255,62,62);}\n"
"#gbxRoleTableHeader{background-color:#FF00A3DA;}\n"
"#gbxRoleTableHeader QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left}\n"
"QListWidget{border:none;background:transparent;}\n"
"QListWidget::item{border-bottom:1px solid black;}\n"
"QListWidget::item .QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left;}\n"
"QListWidget::item .QPushButton{qproperty-alignment: \' AlignHCenter|AlignVCenter\'; font-size:9pt;}\n"
"\n"
"QListWidget::item:hover{background-color:#e5f3ff;}\n"
"QListWidget::item:pressed{background-color:#cde8ff;color:#FF4D4D4D}\n"
"\n"
"#btnRoleAdd{background-color:#FF00A3DA;border:none;}\n"
"#btnRoleAdd:hover{background-color:#8F00A3DA;}\n"
"\n"
"#btnRoleDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#btnRoleDel:hover{background-color:rgb(255, 111, 92);}\n"
"\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical{width:5px;background:transparent;margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:5px;background:rgba(0,0,0,10%);border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:5px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"QCheckBox{background:transparent;}\n"
"QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } \n"
"QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}\n"
"\n"
"#optEdit{color:#4454a6;}\n"
"#optRight{color:#0ab363;}\n"
"#optDel{color:#e54356;}\n"
"\n"
"#optEdit{background-color:#FF00A3DA;border:none;}\n"
"#optEdit:hover{background-color:#8F00A3DA;}\n"
"#optRight{background-color:#05a33a;border:none;}\n"
"#optRight:hover{background-color:#24da10;}\n"
"#optDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#optDel:hover{background-color:rgb(255, 111, 92);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(UiRoleMgr)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_9 = QtWidgets.QGroupBox(UiRoleMgr)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_9.setStyleSheet("")
        self.groupBox_9.setTitle("")
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_9.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(10, -1, 0, -1)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.btnRoleAdd = QtWidgets.QPushButton(self.groupBox_9)
        self.btnRoleAdd.setMinimumSize(QtCore.QSize(80, 30))
        self.btnRoleAdd.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnRoleAdd.setFont(font)
        self.btnRoleAdd.setAutoFillBackground(False)
        self.btnRoleAdd.setStyleSheet("")
        self.btnRoleAdd.setIconSize(QtCore.QSize(16, 16))
        self.btnRoleAdd.setObjectName("btnRoleAdd")
        self.gridLayout_3.addWidget(self.btnRoleAdd, 1, 2, 1, 1)
        self.btnRoleDel = QtWidgets.QPushButton(self.groupBox_9)
        self.btnRoleDel.setMinimumSize(QtCore.QSize(80, 30))
        self.btnRoleDel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnRoleDel.setFont(font)
        self.btnRoleDel.setStyleSheet("")
        self.btnRoleDel.setObjectName("btnRoleDel")
        self.gridLayout_3.addWidget(self.btnRoleDel, 1, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setMinimumSize(QtCore.QSize(0, 40))
        self.label.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineSearch.setMinimumSize(QtCore.QSize(0, 30))
        self.lineSearch.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineSearch.setFont(font)
        self.lineSearch.setTabletTracking(False)
        self.lineSearch.setInputMask("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineSearch.setCursorPosition(0)
        self.lineSearch.setClearButtonEnabled(False)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout_3.addWidget(self.lineSearch, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setMinimumSize(QtCore.QSize(15, 0))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 3, 1, 1)
        self.horizontalLayout_9.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(UiRoleMgr)
        self.groupBox_10.setStyleSheet("")
        self.groupBox_10.setTitle("")
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_7.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_14 = QtWidgets.QGroupBox(self.groupBox_10)
        self.groupBox_14.setStyleSheet("")
        self.groupBox_14.setTitle("")
        self.groupBox_14.setObjectName("groupBox_14")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_14)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gbxRoleTableHeader = QtWidgets.QGroupBox(self.groupBox_14)
        self.gbxRoleTableHeader.setMinimumSize(QtCore.QSize(0, 30))
        self.gbxRoleTableHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gbxRoleTableHeader.setStyleSheet("")
        self.gbxRoleTableHeader.setTitle("")
        self.gbxRoleTableHeader.setObjectName("gbxRoleTableHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxRoleTableHeader)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkAll = QtWidgets.QCheckBox(self.gbxRoleTableHeader)
        self.chkAll.setMinimumSize(QtCore.QSize(40, 20))
        self.chkAll.setMaximumSize(QtCore.QSize(40, 20))
        self.chkAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAll.setStyleSheet("")
        self.chkAll.setText("")
        self.chkAll.setObjectName("chkAll")
        self.horizontalLayout.addWidget(self.chkAll)
        self.label_12 = QtWidgets.QLabel(self.gbxRoleTableHeader)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gbxRoleTableHeader)
        self.label_13.setMinimumSize(QtCore.QSize(560, 0))
        self.label_13.setMaximumSize(QtCore.QSize(560, 16777215))
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.gbxRoleTableHeader)
        self.label_14.setMinimumSize(QtCore.QSize(190, 0))
        self.label_14.setMaximumSize(QtCore.QSize(190, 16777215))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout.addWidget(self.label_14)
        self.verticalLayout_7.addWidget(self.gbxRoleTableHeader)
        self.listWidgetRole = QtWidgets.QListWidget(self.groupBox_14)
        self.listWidgetRole.setStyleSheet("")
        self.listWidgetRole.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.listWidgetRole.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetRole.setAlternatingRowColors(False)
        self.listWidgetRole.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetRole.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetRole.setObjectName("listWidgetRole")
        self.verticalLayout_7.addWidget(self.listWidgetRole)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.horizontalLayout_7.addWidget(self.groupBox_14)
        self.verticalLayout.addWidget(self.groupBox_10)

        self.retranslateUi(UiRoleMgr)
        QtCore.QMetaObject.connectSlotsByName(UiRoleMgr)

    def retranslateUi(self, UiRoleMgr):
        _translate = QtCore.QCoreApplication.translate
        UiRoleMgr.setWindowTitle(_translate("UiRoleMgr", "Form"))
        self.btnRoleAdd.setText(_translate("UiRoleMgr", "添加"))
        self.btnRoleDel.setText(_translate("UiRoleMgr", "批量删除"))
        self.label.setText(_translate("UiRoleMgr", "角色管理"))
        self.lineSearch.setPlaceholderText(_translate("UiRoleMgr", "搜索条件 "))
        self.label_12.setText(_translate("UiRoleMgr", "角色"))
        self.label_13.setText(_translate("UiRoleMgr", "备注"))
        self.label_14.setText(_translate("UiRoleMgr", "操作"))
