# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiSampleMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SampleMgrForm(object):
    def setupUi(self, SampleMgrForm):
        SampleMgrForm.setObjectName("SampleMgrForm")
        SampleMgrForm.resize(1267, 702)
        SampleMgrForm.setStyleSheet(".QGroupBox{border:none;color:white;background-color:#FFFFFF;}\n"
".QPushButton{color:white;background-color:#00A3DA;font-family:\"宋体\";font-szie:11pt;}\n"
".QListWidget{border:none;background:transparent;}\n"
".QLabel{background:transparent; color:white;}\n"
".QCheckBox{background:transparent;margin-left:5px;}\n"
"#gbxLeft{border-right:1px solid gray;}\n"
"#lblTitle{color:white;font-family:\"宋体\";font-size:14pt;}\n"
"#lineSearch{background-color: rgb(50,53,66);color:white;border-radius: 15px; border: 2px;}\n"
"#btnCxDataDel{background-color: rgb(255,62,62);}\n"
"#gbxDemoMgrTableHeader {background-color: #323542;}\n"
"#gbxDemoMgrTableHeader QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left}\n"
"\n"
"QTreeWidget{border:none;background:transparent;color:white;}\n"
"QTreeWidget::item {height:32px;}\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical {width: 5px;}\n"
"QScrollBar:vertical{width:5px;background:#FFFFFF; margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:5px;background:transparent;border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:5px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"QListWidget{border:none;background:transparent;}\n"
"QListWidget::item{border-bottom:1px solid black;}\n"
"QListWidget::item .QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left;}\n"
"QListWidget::item .QPushButton{qproperty-alignment: \' AlignHCenter|AlignVCenter\'; font-size:9pt;}\n"
"\n"
"QCheckBox{background:transparent;}\n"
"QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } \n"
"QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}\n"
"#optView{color:#4454a6;}\n"
"#optExport{color:#0ab363;}\n"
"#optDel{color:#e54356;}\n"
"#btnDemoAdd{color:white;}\n"
"#optView{background-color: rgb(68,99,190);}\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(SampleMgrForm)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbxRight = QtWidgets.QGroupBox(SampleMgrForm)
        self.gbxRight.setStyleSheet("")
        self.gbxRight.setTitle("")
        self.gbxRight.setObjectName("gbxRight")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.gbxRight)
        self.verticalLayout_3.setContentsMargins(0, 15, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_12 = QtWidgets.QGroupBox(self.gbxRight)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 35))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(9, -1, 30, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 0, 3, 1, 1)
        self.btnDemoBatchDel = QtWidgets.QPushButton(self.groupBox_12)
        self.btnDemoBatchDel.setMinimumSize(QtCore.QSize(80, 30))
        self.btnDemoBatchDel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnDemoBatchDel.setFont(font)
        self.btnDemoBatchDel.setStyleSheet("background-color: rgb(255,62,62);\n"
"color:white;")
        self.btnDemoBatchDel.setObjectName("btnDemoBatchDel")
        self.gridLayout_4.addWidget(self.btnDemoBatchDel, 0, 4, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineSearch.setMinimumSize(QtCore.QSize(280, 30))
        self.lineSearch.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineSearch.setFont(font)
        self.lineSearch.setTabletTracking(False)
        self.lineSearch.setStyleSheet("background-color: rgb(50,53,66);\n"
"color:white;\n"
"border-radius: 15px; border: 2px;")
        self.lineSearch.setInputMask("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineSearch.setCursorPosition(0)
        self.lineSearch.setClearButtonEnabled(False)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout_4.addWidget(self.lineSearch, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 1, 1, 1)
        self.btnDemoAdd = QtWidgets.QPushButton(self.groupBox_12)
        self.btnDemoAdd.setMinimumSize(QtCore.QSize(80, 30))
        self.btnDemoAdd.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnDemoAdd.setFont(font)
        self.btnDemoAdd.setStyleSheet("")
        self.btnDemoAdd.setObjectName("btnDemoAdd")
        self.gridLayout_4.addWidget(self.btnDemoAdd, 0, 2, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_4)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(self.gbxRight)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gbxContent = QtWidgets.QGroupBox(self.groupBox_11)
        self.gbxContent.setStyleSheet("")
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.gbxContent)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gbxDemoMgrTableHeader = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxDemoMgrTableHeader.setMinimumSize(QtCore.QSize(0, 30))
        self.gbxDemoMgrTableHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gbxDemoMgrTableHeader.setStyleSheet("")
        self.gbxDemoMgrTableHeader.setTitle("")
        self.gbxDemoMgrTableHeader.setObjectName("gbxDemoMgrTableHeader")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.gbxDemoMgrTableHeader)
        self.horizontalLayout_4.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chkAll = QtWidgets.QCheckBox(self.gbxDemoMgrTableHeader)
        self.chkAll.setMinimumSize(QtCore.QSize(40, 20))
        self.chkAll.setMaximumSize(QtCore.QSize(40, 20))
        self.chkAll.setSizeIncrement(QtCore.QSize(0, 0))
        self.chkAll.setBaseSize(QtCore.QSize(0, 0))
        self.chkAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAll.setStyleSheet("QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}")
        self.chkAll.setText("")
        self.chkAll.setObjectName("chkAll")
        self.horizontalLayout_4.addWidget(self.chkAll)
        self.label_5 = QtWidgets.QLabel(self.gbxDemoMgrTableHeader)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.gbxDemoMgrTableHeader)
        self.label_9.setMinimumSize(QtCore.QSize(100, 0))
        self.label_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_4.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.gbxDemoMgrTableHeader)
        self.label_12.setMinimumSize(QtCore.QSize(180, 0))
        self.label_12.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_4.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gbxDemoMgrTableHeader)
        self.label_13.setMinimumSize(QtCore.QSize(100, 0))
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_4.addWidget(self.label_13)
        self.lblOpt = QtWidgets.QLabel(self.gbxDemoMgrTableHeader)
        self.lblOpt.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lblOpt.setSizeIncrement(QtCore.QSize(100, 0))
        self.lblOpt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOpt.setObjectName("lblOpt")
        self.horizontalLayout_4.addWidget(self.lblOpt)
        self.verticalLayout_7.addWidget(self.gbxDemoMgrTableHeader)
        self.listWidgetDemo = QtWidgets.QListWidget(self.gbxContent)
        self.listWidgetDemo.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.listWidgetDemo.setStyleSheet("")
        self.listWidgetDemo.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetDemo.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetDemo.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetDemo.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetDemo.setObjectName("listWidgetDemo")
        self.verticalLayout_7.addWidget(self.listWidgetDemo)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addWidget(self.gbxContent)
        self.verticalLayout_3.addWidget(self.groupBox_11)
        self.horizontalLayout.addWidget(self.gbxRight)

        self.retranslateUi(SampleMgrForm)
        QtCore.QMetaObject.connectSlotsByName(SampleMgrForm)

    def retranslateUi(self, SampleMgrForm):
        _translate = QtCore.QCoreApplication.translate
        SampleMgrForm.setWindowTitle(_translate("SampleMgrForm", "Form"))
        self.btnDemoBatchDel.setText(_translate("SampleMgrForm", "批量删除"))
        self.lineSearch.setPlaceholderText(_translate("SampleMgrForm", "搜索条件 "))
        self.btnDemoAdd.setText(_translate("SampleMgrForm", "添加"))
        self.label_5.setText(_translate("SampleMgrForm", "样品号"))
        self.label_9.setText(_translate("SampleMgrForm", "样品名称"))
        self.label_12.setText(_translate("SampleMgrForm", "创建时间"))
        self.label_13.setText(_translate("SampleMgrForm", "备注"))
        self.lblOpt.setText(_translate("SampleMgrForm", "操作"))
