# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiSampleAdd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 400)
        Form.setStyleSheet("QGroupBox{border:none}\n"
"QLabel{background-color:transparent;color:white;}\n"
"QPushButton{background-color:transparent;color:white;font-family:\"宋体\";font-size:10pt;}\n"
"QLineEdit,QPlainTextEdit{background-color: rgb(50, 53, 66);color:white;border:none;}\n"
"#lblFormName{font-family:\"宋体\";font-size:14pt;}\n"
"#lblTitle{font-family:\"宋体\";font-size:10pt;}\n"
"#gbxTop{background-color:#323542}\n"
"#gbxContent{background-color:#444756}\n"
"#gbxClose{background-color:transparent;}\n"
"#btnOk{background-color:#4463be;color:white;}\n"
"#gbxContent{border:1px solid gray;}\n"
"#btnClose{border-image: url(./Res/叉.png)}\n"
"#btnOpenFile{border-image:url(./Res/folder.png)}\n"
"\n"
"\n"
"")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gbxContent = QtWidgets.QGroupBox(Form)
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbxContent)
        self.verticalLayout.setContentsMargins(2, 2, 2, 15)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbxTop = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxTop.setMinimumSize(QtCore.QSize(0, 50))
        self.gbxTop.setMaximumSize(QtCore.QSize(16777215, 50))
        self.gbxTop.setTitle("")
        self.gbxTop.setObjectName("gbxTop")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxTop)
        self.horizontalLayout.setContentsMargins(20, -1, 30, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblFormName = QtWidgets.QLabel(self.gbxTop)
        self.lblFormName.setObjectName("lblFormName")
        self.horizontalLayout.addWidget(self.lblFormName)
        self.btnClose = QtWidgets.QPushButton(self.gbxTop)
        self.btnClose.setMinimumSize(QtCore.QSize(20, 20))
        self.btnClose.setMaximumSize(QtCore.QSize(20, 20))
        self.btnClose.setText("")
        self.btnClose.setObjectName("btnClose")
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addWidget(self.gbxTop)
        self.gbxBottom = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxBottom.setTitle("")
        self.gbxBottom.setObjectName("gbxBottom")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.gbxBottom)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.gbxBottom)
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, 6)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setVerticalSpacing(15)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox_3)
        self.label.setMaximumSize(QtCore.QSize(80, 32))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtSampleNo = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtSampleNo.setMinimumSize(QtCore.QSize(250, 30))
        self.txtSampleNo.setMaximumSize(QtCore.QSize(250, 32))
        self.txtSampleNo.setObjectName("txtSampleNo")
        self.gridLayout.addWidget(self.txtSampleNo, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_3)
        self.label_2.setMaximumSize(QtCore.QSize(80, 32))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txtSampleName = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtSampleName.setMinimumSize(QtCore.QSize(250, 30))
        self.txtSampleName.setMaximumSize(QtCore.QSize(250, 32))
        self.txtSampleName.setObjectName("txtSampleName")
        self.gridLayout.addWidget(self.txtSampleName, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setMaximumSize(QtCore.QSize(80, 32))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.txtSampleFile = QtWidgets.QLineEdit(self.groupBox_3)
        self.txtSampleFile.setMinimumSize(QtCore.QSize(250, 30))
        self.txtSampleFile.setMaximumSize(QtCore.QSize(250, 32))
        self.txtSampleFile.setObjectName("txtSampleFile")
        self.gridLayout.addWidget(self.txtSampleFile, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(80, 32))
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtSampleComment = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.txtSampleComment.setMinimumSize(QtCore.QSize(250, 0))
        self.txtSampleComment.setMaximumSize(QtCore.QSize(250, 120))
        self.txtSampleComment.setObjectName("txtSampleComment")
        self.gridLayout.addWidget(self.txtSampleComment, 3, 1, 1, 1)
        self.btnOpenFile = QtWidgets.QPushButton(self.groupBox_3)
        self.btnOpenFile.setMinimumSize(QtCore.QSize(20, 17))
        self.btnOpenFile.setMaximumSize(QtCore.QSize(20, 17))
        self.btnOpenFile.setText("")
        self.btnOpenFile.setObjectName("btnOpenFile")
        self.gridLayout.addWidget(self.btnOpenFile, 2, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gbxBottom)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnOk = QtWidgets.QPushButton(self.groupBox_2)
        self.btnOk.setMinimumSize(QtCore.QSize(80, 30))
        self.btnOk.setMaximumSize(QtCore.QSize(80, 30))
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_2.addWidget(self.btnOk)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.verticalLayout.addWidget(self.gbxBottom)
        self.horizontalLayout_6.addWidget(self.gbxContent)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblFormName.setText(_translate("Form", "添加样品信息"))
        self.label.setText(_translate("Form", "样品编号:"))
        self.label_2.setText(_translate("Form", "样品名称:"))
        self.label_3.setText(_translate("Form", "样品文件:"))
        self.label_4.setText(_translate("Form", "备    注:"))
        self.btnOk.setText(_translate("Form", "确 定"))
