# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiSysParamsSetting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1264, 701)
        Form.setStyleSheet("QGroupBox{background-color: rgb(68, 71, 86);}\n"
"QGroupBox>QLabel{color:white;background:transparent;}\n"
"QGroupBox>QLineEdit{background-color: rgb(50, 53, 66);color:white;border:none;}\n"
"QGroupBox>QPushButton{color:white;}\n"
"#btnSave{background-color: rgb(68,99,190);}\n"
"QComboBox{color:white;}\n"
"QComboBox QAbstractItemView::item {color:white;}\n"
"\n"
"\n"
"")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(10)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.cbxDataBaseVer = QtWidgets.QComboBox(self.groupBox)
        self.cbxDataBaseVer.setMinimumSize(QtCore.QSize(100, 30))
        self.cbxDataBaseVer.setObjectName("cbxDataBaseVer")
        self.cbxDataBaseVer.addItem("")
        self.cbxDataBaseVer.addItem("")
        self.cbxDataBaseVer.addItem("")
        self.cbxDataBaseVer.addItem("")
        self.cbxDataBaseVer.addItem("")
        self.gridLayout.addWidget(self.cbxDataBaseVer, 3, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 1, 1, 1)
        self.btnSave = QtWidgets.QPushButton(self.groupBox)
        self.btnSave.setMinimumSize(QtCore.QSize(80, 30))
        self.btnSave.setMaximumSize(QtCore.QSize(80, 30))
        self.btnSave.setObjectName("btnSave")
        self.gridLayout.addWidget(self.btnSave, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.cbxDataSaveTime = QtWidgets.QComboBox(self.groupBox)
        self.cbxDataSaveTime.setMinimumSize(QtCore.QSize(100, 30))
        self.cbxDataSaveTime.setObjectName("cbxDataSaveTime")
        self.cbxDataSaveTime.addItem("")
        self.cbxDataSaveTime.addItem("")
        self.cbxDataSaveTime.addItem("")
        self.cbxDataSaveTime.addItem("")
        self.cbxDataSaveTime.addItem("")
        self.gridLayout.addWidget(self.cbxDataSaveTime, 2, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 3, 1, 1)
        self.cbxLogSaveTime = QtWidgets.QComboBox(self.groupBox)
        self.cbxLogSaveTime.setMinimumSize(QtCore.QSize(100, 30))
        self.cbxLogSaveTime.setObjectName("cbxLogSaveTime")
        self.cbxLogSaveTime.addItem("")
        self.cbxLogSaveTime.addItem("")
        self.cbxLogSaveTime.addItem("")
        self.cbxLogSaveTime.addItem("")
        self.cbxLogSaveTime.addItem("")
        self.gridLayout.addWidget(self.cbxLogSaveTime, 1, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.txtDataSavePath = QtWidgets.QLineEdit(self.groupBox)
        self.txtDataSavePath.setMinimumSize(QtCore.QSize(100, 30))
        self.txtDataSavePath.setObjectName("txtDataSavePath")
        self.gridLayout.addWidget(self.txtDataSavePath, 4, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cbxDataBaseVer.setItemText(0, _translate("Form", "光谱"))
        self.cbxDataBaseVer.setItemText(1, _translate("Form", "光谱成像"))
        self.cbxDataBaseVer.setItemText(2, _translate("Form", "成像"))
        self.cbxDataBaseVer.setItemText(3, _translate("Form", "光谱成像+成像"))
        self.cbxDataBaseVer.setItemText(4, _translate("Form", "所有"))
        self.label_4.setText(_translate("Form", "数据保存路径:"))
        self.btnSave.setText(_translate("Form", "保 存"))
        self.label_3.setText(_translate("Form", "数据库版本:"))
        self.label_2.setText(_translate("Form", "数据保留时间:"))
        self.cbxDataSaveTime.setItemText(0, _translate("Form", "一周"))
        self.cbxDataSaveTime.setItemText(1, _translate("Form", "半月"))
        self.cbxDataSaveTime.setItemText(2, _translate("Form", "一月"))
        self.cbxDataSaveTime.setItemText(3, _translate("Form", "二月"))
        self.cbxDataSaveTime.setItemText(4, _translate("Form", "三月"))
        self.cbxLogSaveTime.setItemText(0, _translate("Form", "一周"))
        self.cbxLogSaveTime.setItemText(1, _translate("Form", "半月"))
        self.cbxLogSaveTime.setItemText(2, _translate("Form", "一月"))
        self.cbxLogSaveTime.setItemText(3, _translate("Form", "二月"))
        self.cbxLogSaveTime.setItemText(4, _translate("Form", "三月"))
        self.label.setText(_translate("Form", "日志保留时间:"))
