# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiSysOptLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SysOptLogForm(object):
    def setupUi(self, SysOptLogForm):
        SysOptLogForm.setObjectName("SysOptLogForm")
        SysOptLogForm.resize(1264, 702)
        SysOptLogForm.setStyleSheet("QGroupBox{border:none;background-color:#FFFFFF;}\n"
"QPushButton{font-family:\"宋体\";font-size:11pt;color:white;background:transparent;}\n"
"QCheckBox{background:transparent;margin-left:5px;}\n"
"QDateEdit{background-color:#FFEBEBEB;border:none;font-family:\"宋体\";font-size:10pt;}\n"
"QDateEdit::drop-down {image: url(./Res/calendar.png);width:30px;height:30px;subcontrol-position: right top;subcontrol-origin:margin;}\n"
"QComboBox{color:#FF4D4D4D;}\n"
"QComboBox QAbstractItemView::item { height: 25px; color:#FF4D4D4D; }\n"
"QScrollArea{background:transparent;border:none;}\n"
"#scrollAreaWidgetContents{background-color:#FFFFFF;}\n"
"#lineSearch{background-color:#FFEBEBEB;color:#FF4D4D4D;border-radius: 15px; border: 2px; padding:0 0 0 10;}\n"
"#btnDel{background-color: rgb(255,62,62);}\n"
"#btnExport{background-color: rgb(68,99,190);}\n"
"#btnPrev{background-color: rgb(68,99,190);}\n"
"#btnNext{background-color: rgb(68,99,190);}\n"
"#gbxSysLogTableHeader{background-color: #FF00A3DA;}\n"
"#gbxSysLogTableHeader QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;}\n"
"#btnExport{background-color:#FF00A3DA;border:none;}\n"
"#btnExport:hover{background-color:#8F00A3DA;}\n"
"#btnDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#btnDel:hover{background-color:rgb(255, 111, 92);}\n"
"#btnPrev{background-color:#FF00A3DA;border:none;}\n"
"#btnPrev:hover{background-color:#8F00A3DA;}\n"
"#btnNext{background-color:#FF00A3DA;border:none;}\n"
"#btnNext:hover{background-color:#8F00A3DA;}\n"
"\n"
"QListWidget{border:none;background:transparent;}\n"
"QListWidget::item{border-bottom:1px solid black;}\n"
"QListWidget::item .QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;qproperty-min-height:50px;}\n"
"QListWidget::item .QPushButton{qproperty-alignment: \' AlignHCenter|AlignVCenter\'; font-size:9pt;}\n"
"QListWidget::item:hover{background-color:#e5f3ff;}\n"
"QListWidget::item:pressed{background-color:#cde8ff;color:#FF4D4D4D}\n"
"\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical {width: 5px;}\n"
"QScrollBar:vertical{width:5px;background:#FFFFFF; margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:5px;background:transparent;border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:5px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"QCheckBox{background:transparent;}\n"
"QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } \n"
"QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}\n"
"#optView{color:#4454a6;}\n"
"#optExport{color:#0ab363;}\n"
"#optDel{color:#e54356;}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(SysOptLogForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_12 = QtWidgets.QGroupBox(SysOptLogForm)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(9, -1, 30, 10)
        self.gridLayout_4.setHorizontalSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.deEnd = QtWidgets.QDateEdit(self.groupBox_12)
        self.deEnd.setMinimumSize(QtCore.QSize(120, 30))
        self.deEnd.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.deEnd.setFont(font)
        self.deEnd.setCalendarPopup(True)
        self.deEnd.setObjectName("deEnd")
        self.gridLayout_4.addWidget(self.deEnd, 1, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.btnExport = QtWidgets.QPushButton(self.groupBox_12)
        self.btnExport.setMinimumSize(QtCore.QSize(80, 30))
        self.btnExport.setMaximumSize(QtCore.QSize(80, 30))
        self.btnExport.setObjectName("btnExport")
        self.gridLayout_4.addWidget(self.btnExport, 1, 6, 1, 1)
        self.btnDel = QtWidgets.QPushButton(self.groupBox_12)
        self.btnDel.setMinimumSize(QtCore.QSize(80, 30))
        self.btnDel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnDel.setFont(font)
        self.btnDel.setStyleSheet("")
        self.btnDel.setObjectName("btnDel")
        self.gridLayout_4.addWidget(self.btnDel, 1, 8, 1, 1)
        self.deBegin = QtWidgets.QDateEdit(self.groupBox_12)
        self.deBegin.setMinimumSize(QtCore.QSize(120, 0))
        self.deBegin.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(10)
        self.deBegin.setFont(font)
        self.deBegin.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.deBegin.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.deBegin.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 2, 16), QtCore.QTime(7, 41, 0)))
        self.deBegin.setTime(QtCore.QTime(7, 41, 0))
        self.deBegin.setCalendarPopup(True)
        self.deBegin.setTimeSpec(QtCore.Qt.UTC)
        self.deBegin.setObjectName("deBegin")
        self.gridLayout_4.addWidget(self.deBegin, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 5, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 7, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineSearch.setMinimumSize(QtCore.QSize(280, 30))
        self.lineSearch.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineSearch.setFont(font)
        self.lineSearch.setTabletTracking(False)
        self.lineSearch.setStyleSheet("")
        self.lineSearch.setInputMask("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineSearch.setCursorPosition(0)
        self.lineSearch.setClearButtonEnabled(False)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout_4.addWidget(self.lineSearch, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_12)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_12)
        self.label_2.setMinimumSize(QtCore.QSize(15, 0))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 1, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(SysOptLogForm)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gbxContent = QtWidgets.QGroupBox(self.groupBox_11)
        self.gbxContent.setStyleSheet("")
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.gbxContent)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.scrollArea = QtWidgets.QScrollArea(self.gbxContent)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1262, 578))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxSysLogTableHeader = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.gbxSysLogTableHeader.setMinimumSize(QtCore.QSize(0, 30))
        self.gbxSysLogTableHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gbxSysLogTableHeader.setStyleSheet("")
        self.gbxSysLogTableHeader.setTitle("")
        self.gbxSysLogTableHeader.setObjectName("gbxSysLogTableHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxSysLogTableHeader)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkAll = QtWidgets.QCheckBox(self.gbxSysLogTableHeader)
        self.chkAll.setMinimumSize(QtCore.QSize(40, 20))
        self.chkAll.setMaximumSize(QtCore.QSize(40, 20))
        self.chkAll.setSizeIncrement(QtCore.QSize(0, 0))
        self.chkAll.setBaseSize(QtCore.QSize(0, 0))
        self.chkAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAll.setStyleSheet("")
        self.chkAll.setText("")
        self.chkAll.setObjectName("chkAll")
        self.horizontalLayout.addWidget(self.chkAll)
        self.label_5 = QtWidgets.QLabel(self.gbxSysLogTableHeader)
        self.label_5.setMinimumSize(QtCore.QSize(180, 0))
        self.label_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.gbxSysLogTableHeader)
        self.label_9.setMinimumSize(QtCore.QSize(80, 0))
        self.label_9.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.gbxSysLogTableHeader)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gbxSysLogTableHeader)
        self.label_13.setMinimumSize(QtCore.QSize(500, 0))
        self.label_13.setMaximumSize(QtCore.QSize(500, 16777215))
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.verticalLayout_2.addWidget(self.gbxSysLogTableHeader)
        self.listWidgetLogs = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidgetLogs.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.listWidgetLogs.setStyleSheet("")
        self.listWidgetLogs.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetLogs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetLogs.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetLogs.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetLogs.setObjectName("listWidgetLogs")
        self.verticalLayout_2.addWidget(self.listWidgetLogs)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.groupBox = QtWidgets.QGroupBox(self.gbxContent)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnPrev = QtWidgets.QPushButton(self.groupBox)
        self.btnPrev.setMinimumSize(QtCore.QSize(80, 30))
        self.btnPrev.setMaximumSize(QtCore.QSize(80, 30))
        self.btnPrev.setObjectName("btnPrev")
        self.horizontalLayout_2.addWidget(self.btnPrev)
        self.cbxPages = QtWidgets.QComboBox(self.groupBox)
        self.cbxPages.setMinimumSize(QtCore.QSize(80, 32))
        self.cbxPages.setMaximumSize(QtCore.QSize(80, 32))
        self.cbxPages.setSizeIncrement(QtCore.QSize(0, 0))
        self.cbxPages.setStyleSheet("background-color: #FFEBEBEB; border:none;")
        self.cbxPages.setEditable(False)
        self.cbxPages.setCurrentText("")
        self.cbxPages.setPlaceholderText("")
        self.cbxPages.setObjectName("cbxPages")
        self.horizontalLayout_2.addWidget(self.cbxPages)
        self.btnNext = QtWidgets.QPushButton(self.groupBox)
        self.btnNext.setMinimumSize(QtCore.QSize(80, 30))
        self.btnNext.setMaximumSize(QtCore.QSize(80, 30))
        self.btnNext.setObjectName("btnNext")
        self.horizontalLayout_2.addWidget(self.btnNext)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addWidget(self.gbxContent)
        self.verticalLayout.addWidget(self.groupBox_11)

        self.retranslateUi(SysOptLogForm)
        QtCore.QMetaObject.connectSlotsByName(SysOptLogForm)

    def retranslateUi(self, SysOptLogForm):
        _translate = QtCore.QCoreApplication.translate
        SysOptLogForm.setWindowTitle(_translate("SysOptLogForm", "Form"))
        self.label_4.setText(_translate("SysOptLogForm", "系统操作日志"))
        self.btnExport.setText(_translate("SysOptLogForm", "导  出"))
        self.btnDel.setText(_translate("SysOptLogForm", "批量删除"))
        self.lineSearch.setPlaceholderText(_translate("SysOptLogForm", "搜索条件"))
        self.label.setText(_translate("SysOptLogForm", "—"))
        self.label_5.setText(_translate("SysOptLogForm", "姓名"))
        self.label_9.setText(_translate("SysOptLogForm", "类型"))
        self.label_12.setText(_translate("SysOptLogForm", "时间"))
        self.label_13.setText(_translate("SysOptLogForm", "操作内容"))
        self.btnPrev.setText(_translate("SysOptLogForm", "上一页"))
        self.btnNext.setText(_translate("SysOptLogForm", "下一页"))
