# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UiUserMgr.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UiUserMgrForm(object):
    def setupUi(self, UiUserMgrForm):
        UiUserMgrForm.setObjectName("UiUserMgrForm")
        UiUserMgrForm.resize(1101, 658)
        UiUserMgrForm.setStyleSheet(".QGroupBox{border:none;background-color:#FFFFFF;}\n"
".QPushButton{font-size:11pt;color:white;}\n"
".QCheckBox{background:transparent;margin-left:5px;}\n"
"#lineSearch{background-color:#FFEBEBEB;color:#FF4D4D4D;border-radius: 15px; border: 2px; padding:0 0 0 10;}\n"
"#btnUserAdd{background-color: rgb(68,99,190);}\n"
"#btnUserDel{background-color: rgb(255,62,62);}\n"
"#gbxUserTableHeader{background-color: #FF00A3DA;}\n"
"#gbxUserTableHeader QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left}\n"
"QListWidget{border:none;background:transparent;}\n"
"QListWidget::item{border-bottom:1px solid black;}\n"
"QListWidget::item .QLabel{qproperty-alignment: \'AlignHCenter|AlignVCenter\';font-size:9pt;text-align:left;}\n"
"QListWidget::item .QPushButton{qproperty-alignment: \' AlignHCenter|AlignVCenter\'; font-size:9pt;}\n"
"\n"
"QListWidget::item:hover{background-color:#e5f3ff;}\n"
"QListWidget::item:pressed{background-color:#cde8ff;color:#FF4D4D4D}\n"
"\n"
"#btnUserAdd{background-color:#FF00A3DA;border:none;}\n"
"#btnUserAdd:hover{background-color:#8F00A3DA;}\n"
"\n"
"#btnUserDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#btnUserDel:hover{background-color:rgb(255, 111, 92);}\n"
"\n"
"QScrollBar{border:none;background:transparent;}\n"
"QScrollBar:vertical{width:3px;background:transparent;margin:0px,0px,0px,0px;padding-top:0px;padding-bottom:0px;}\n"
"QScrollBar::handle:vertical{width:3px;background:rgba(0,0,0,10%);border-radius:4px;min-height:60;}\n"
"QScrollBar::handle:vertical:hover{width:3px;background:rgba(0,0,0,20%);border-radius:4px;min-height:60;}\n"
"QScrollBar::add-line:vertical{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::add-line:vertical:hover{height:0px;width:0px;subcontrol-position:bottom;}\n"
"QScrollBar::sub-line:vertical:hover{height:0px;width:0px;subcontrol-position:top;}\n"
"QScrollBar::sub-page:vertical{background: none;}\n"
"QScrollBar::add-page:vertical{background: none;}\n"
"\n"
"QCheckBox{background:transparent;}\n"
"QCheckBox::indicator { width: 20px;height: 20px;}\n"
"QCheckBox::indicator:checked { image: url(./Res/checkbox-checked.png); } \n"
"QCheckBox::indicator:unchecked {image: url(./Res/checkbox-unchecked.png);}\n"
"\n"
"#optEdit{color:#4454a6;}\n"
"#optResetPwd{color:#0ab363;}\n"
"#optDel{color:#e54356;}\n"
"\n"
"#optEdit{background-color:#FF00A3DA;border:none;}\n"
"#optEdit:hover{background-color:#8F00A3DA;}\n"
"#optResetPwd{background-color:#05a33a;border:none;}\n"
"#optResetPwd:hover{background-color:#24da10;}\n"
"#optDel{background-color: rgb(255, 2, 2);border:none;}\n"
"#optDel:hover{background-color:rgb(255, 111, 92);}")
        self.verticalLayout = QtWidgets.QVBoxLayout(UiUserMgrForm)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_12 = QtWidgets.QGroupBox(UiUserMgrForm)
        self.groupBox_12.setMinimumSize(QtCore.QSize(0, 80))
        self.groupBox_12.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox_12.setTitle("")
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_15.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(10, -1, 0, -1)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox_12)
        self.label_4.setMinimumSize(QtCore.QSize(0, 40))
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:white;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.btnUserAdd = QtWidgets.QPushButton(self.groupBox_12)
        self.btnUserAdd.setMinimumSize(QtCore.QSize(80, 30))
        self.btnUserAdd.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnUserAdd.setFont(font)
        self.btnUserAdd.setStyleSheet("")
        self.btnUserAdd.setObjectName("btnUserAdd")
        self.gridLayout_4.addWidget(self.btnUserAdd, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_12)
        self.label_6.setMinimumSize(QtCore.QSize(15, 0))
        self.label_6.setMaximumSize(QtCore.QSize(15, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 3, 1, 1)
        self.btnUserDel = QtWidgets.QPushButton(self.groupBox_12)
        self.btnUserDel.setMinimumSize(QtCore.QSize(80, 30))
        self.btnUserDel.setMaximumSize(QtCore.QSize(80, 30))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.btnUserDel.setFont(font)
        self.btnUserDel.setStyleSheet("")
        self.btnUserDel.setObjectName("btnUserDel")
        self.gridLayout_4.addWidget(self.btnUserDel, 1, 4, 1, 1)
        self.lineSearch = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineSearch.setMinimumSize(QtCore.QSize(280, 30))
        self.lineSearch.setMaximumSize(QtCore.QSize(280, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineSearch.setFont(font)
        self.lineSearch.setTabletTracking(False)
        self.lineSearch.setStyleSheet("")
        self.lineSearch.setInputMask("")
        self.lineSearch.setMaxLength(32767)
        self.lineSearch.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineSearch.setCursorPosition(0)
        self.lineSearch.setClearButtonEnabled(False)
        self.lineSearch.setObjectName("lineSearch")
        self.gridLayout_4.addWidget(self.lineSearch, 1, 0, 1, 1)
        self.horizontalLayout_15.addLayout(self.gridLayout_4)
        self.verticalLayout.addWidget(self.groupBox_12)
        self.groupBox_11 = QtWidgets.QGroupBox(UiUserMgrForm)
        self.groupBox_11.setStyleSheet("")
        self.groupBox_11.setTitle("")
        self.groupBox_11.setObjectName("groupBox_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.groupBox_11)
        self.horizontalLayout_9.setContentsMargins(0, 9, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gbxContent = QtWidgets.QGroupBox(self.groupBox_11)
        self.gbxContent.setStyleSheet("")
        self.gbxContent.setTitle("")
        self.gbxContent.setObjectName("gbxContent")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.gbxContent)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gbxUserTableHeader = QtWidgets.QGroupBox(self.gbxContent)
        self.gbxUserTableHeader.setMinimumSize(QtCore.QSize(0, 30))
        self.gbxUserTableHeader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.gbxUserTableHeader.setStyleSheet("")
        self.gbxUserTableHeader.setTitle("")
        self.gbxUserTableHeader.setObjectName("gbxUserTableHeader")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.gbxUserTableHeader)
        self.horizontalLayout.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.chkAll = QtWidgets.QCheckBox(self.gbxUserTableHeader)
        self.chkAll.setMinimumSize(QtCore.QSize(40, 20))
        self.chkAll.setMaximumSize(QtCore.QSize(40, 20))
        self.chkAll.setSizeIncrement(QtCore.QSize(0, 0))
        self.chkAll.setBaseSize(QtCore.QSize(40, 20))
        self.chkAll.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.chkAll.setStyleSheet("")
        self.chkAll.setText("")
        self.chkAll.setObjectName("chkAll")
        self.horizontalLayout.addWidget(self.chkAll)
        self.label_5 = QtWidgets.QLabel(self.gbxUserTableHeader)
        self.label_5.setMinimumSize(QtCore.QSize(180, 0))
        self.label_5.setMaximumSize(QtCore.QSize(180, 16777215))
        self.label_5.setStyleSheet("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(self.gbxUserTableHeader)
        self.label_9.setMinimumSize(QtCore.QSize(200, 0))
        self.label_9.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_9.setStyleSheet("")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.label_12 = QtWidgets.QLabel(self.gbxUserTableHeader)
        self.label_12.setMinimumSize(QtCore.QSize(200, 0))
        self.label_12.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_12.setStyleSheet("")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(self.gbxUserTableHeader)
        self.label_13.setMinimumSize(QtCore.QSize(220, 0))
        self.label_13.setMaximumSize(QtCore.QSize(220, 16777215))
        self.label_13.setStyleSheet("")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.lblOpt = QtWidgets.QLabel(self.gbxUserTableHeader)
        self.lblOpt.setMinimumSize(QtCore.QSize(170, 0))
        self.lblOpt.setMaximumSize(QtCore.QSize(170, 16777215))
        self.lblOpt.setSizeIncrement(QtCore.QSize(0, 0))
        self.lblOpt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblOpt.setObjectName("lblOpt")
        self.horizontalLayout.addWidget(self.lblOpt)
        self.verticalLayout_7.addWidget(self.gbxUserTableHeader)
        self.listWidgetUser = QtWidgets.QListWidget(self.gbxContent)
        self.listWidgetUser.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.listWidgetUser.setStyleSheet("")
        self.listWidgetUser.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidgetUser.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetUser.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listWidgetUser.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidgetUser.setObjectName("listWidgetUser")
        self.verticalLayout_7.addWidget(self.listWidgetUser)
        self.horizontalLayout_19.addLayout(self.verticalLayout_7)
        self.horizontalLayout_9.addWidget(self.gbxContent)
        self.verticalLayout.addWidget(self.groupBox_11)

        self.retranslateUi(UiUserMgrForm)
        QtCore.QMetaObject.connectSlotsByName(UiUserMgrForm)

    def retranslateUi(self, UiUserMgrForm):
        _translate = QtCore.QCoreApplication.translate
        UiUserMgrForm.setWindowTitle(_translate("UiUserMgrForm", "Form"))
        self.label_4.setText(_translate("UiUserMgrForm", "用户管理"))
        self.btnUserAdd.setText(_translate("UiUserMgrForm", "添加"))
        self.btnUserDel.setText(_translate("UiUserMgrForm", "批量删除"))
        self.lineSearch.setPlaceholderText(_translate("UiUserMgrForm", "搜索条件 "))
        self.label_5.setText(_translate("UiUserMgrForm", "姓名"))
        self.label_9.setText(_translate("UiUserMgrForm", "手机号"))
        self.label_12.setText(_translate("UiUserMgrForm", "角色"))
        self.label_13.setText(_translate("UiUserMgrForm", "备注"))
        self.lblOpt.setText(_translate("UiUserMgrForm", "操作"))
